language: python

env:
    global:
        - UNICODE_WIDTH=32
        - PLAT=x86_64
    matrix:
        - MB_PYTHON_VERSION=2.7
        - MB_PYTHON_VERSION=3.4
        - MB_PYTHON_VERSION=3.5
        - MB_PYTHON_VERSION=3.6
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

services: docker
sudo: required

matrix:
    exclude:
        - os: osx
        - os: linux
          compiler: clang
    include:
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=2.7
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.4
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.5
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.6

addons:
    apt:
      sources:
        - sourceline: 'ppa:sisib/ci-backports'
        - george-edison55-precise-backports # cmake 3
      packages:
        - valgrind
        - cppcheck
        - cmake
        - cmake-data

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
  # on os x, python is set up in a virtualenv, but cmake tends to find a
  # system-installed, incompatible python lib.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update && brew install cppcheck;
      prefix=`python-config --prefix`;
      ext=`python-config --extension`;
      pylib=$prefix/lib/libpython$MB_PYTHON_VERSION.$ext;
    fi
  - pip install numpy --upgrade

before_script:
  - enabled="-DBUILD_PYTHON=OFF -DBUILD_MEX=OFF"
  - if [[ -n "${MB_PYTHON_VERSION+1}" ]]; then
        enabled="$enabled -DBUILD_PYTHON=ON";
        if [[ $TRAVIS_OS_NAME == osx ]]; then
            pylib="-DPYTHON_LIBRARY=$pylib"
        fi;
    fi
  - cmake --version
  - mkdir build
  - pushd build
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DBUILD_SHARED_LIBS=ON
          $pylib
          $enabled  ..
  - cppcheck --language=c
             --std=c99
             --enable=style,portability,performance,warning
             --library=posix
             --library=$TRAVIS_BUILD_DIR/cppcheck/segyio.cfg
             --suppressions-list=$TRAVIS_BUILD_DIR/cppcheck/suppressions.txt
             --inline-suppr
             --project=compile_commands.json
             --error-exitcode=1
script:
  - make && ctest --output-on-failure
  - cat python/setup.py
  - popd
  - BUILD_COMMANDS=build_bdist_wheel build_wheel build/python
  - install_run $PLAT
  - mv wheelhouse build/python/dist

before_deploy:
    - pushd build/python

after_deploy:
    - popd

deploy:
    - provider: pypi # source distribution (done from linux python 3.6 only)
      skip_cleanup: true
      skip_upload_docs: true
      user: statoil-travis
      password:
        secure: WHeA5x2iiXzjYXdgZeJU6l4fawRi/umqH1713QAj0RPZBAnD+9m8Zrpn2UWn9+1dtx6xUMkNg3ZTueVKTKo0f2i/4o0xkzQ5BW11cetCWusV2Dku1btPTA5Fhs+dvPDlL3m496a3Bq/A/fRDj5JLDiiPibvpM01lEBxFKYooWGQ75HVuhnAt57vabD45gDpIE7N23+So4+9bsG/nT/ZlgoaS01uLTdlnf6tjNgP0/UBkonmedC62iVvCu7itfHZMTY2rSeww7KBMI3s7Gz+cyx9IbI3shbDpdJGHpM8Qe+1oFi31Z+DylWQA5SkpHlLMUP+zjMKLF+1hXGNUeJuyadIFrxzbS3vTV2yRPa6ol8q+bX7YLy0xNLSE8aMm54LKgXfRKLc3G8d3I33oEfyk5hygY8iEX728r2TsARslYxOF3sZqJvY8lx4GBEDiXxX2GJvGCPy/Uby786uWnZlFFkDERk3nawE0W68zY0GElbutq6HMSk6v49J7em9Rg/QLptjoa0uF2A9Cy+BAJcnfauIawOG3UPXZ8kD60PTbu8tqtwtXO5lzTSIOr1lt3+6R8GmCc2hz2YXELKvdnZWYCXAjnNuC4eESlp7zxmzhpOVkb2Jy1v6rGKpcxVMggLQbOjOGWPLg9q4+OZQBw5bhMGmVGQhSBuxzEb/wBRy9XV8=
      on:
        condition: $TRAVIS_OS_NAME == linux && $MB_PYTHON_VERSION == 3.6
        branch: update-pycmake-generate-setup-py

    - provider: pypi # upload built wheels
      skip_cleanup: true
      skip_upload_docs: true
      user: statoil-travis
      distributions: build
      password:
        secure: WHeA5x2iiXzjYXdgZeJU6l4fawRi/umqH1713QAj0RPZBAnD+9m8Zrpn2UWn9+1dtx6xUMkNg3ZTueVKTKo0f2i/4o0xkzQ5BW11cetCWusV2Dku1btPTA5Fhs+dvPDlL3m496a3Bq/A/fRDj5JLDiiPibvpM01lEBxFKYooWGQ75HVuhnAt57vabD45gDpIE7N23+So4+9bsG/nT/ZlgoaS01uLTdlnf6tjNgP0/UBkonmedC62iVvCu7itfHZMTY2rSeww7KBMI3s7Gz+cyx9IbI3shbDpdJGHpM8Qe+1oFi31Z+DylWQA5SkpHlLMUP+zjMKLF+1hXGNUeJuyadIFrxzbS3vTV2yRPa6ol8q+bX7YLy0xNLSE8aMm54LKgXfRKLc3G8d3I33oEfyk5hygY8iEX728r2TsARslYxOF3sZqJvY8lx4GBEDiXxX2GJvGCPy/Uby786uWnZlFFkDERk3nawE0W68zY0GElbutq6HMSk6v49J7em9Rg/QLptjoa0uF2A9Cy+BAJcnfauIawOG3UPXZ8kD60PTbu8tqtwtXO5lzTSIOr1lt3+6R8GmCc2hz2YXELKvdnZWYCXAjnNuC4eESlp7zxmzhpOVkb2Jy1v6rGKpcxVMggLQbOjOGWPLg9q4+OZQBw5bhMGmVGQhSBuxzEb/wBRy9XV8=
      on:
        branch: update-pycmake-generate-setup-py
